---
# tasks file for opstree.mongo

- name: Creates backup directory ...
  file: path={{ mongo_backup_dir }} state=directory

- name: mongo backup ...
  command: mongodump --out {{ mongo_backup_dir }}
  when: password_less_login

- name: mongo backup ...
  command: mongodump --username {{ mongo_database_username }} --password {{ mongo_database_passwd }} --out {{ mongo_backup_dir }}
  when: password_login

- name: mongo backup ..
  command: mongodump --username {{ mongo_database_username }} --db {{ mongo_database_name }} --password {{ mongo_database_passwd }} --out {{ mongo_backup_dir }}
  when: backup_for_spaecfice_database

- name: mongo backup ..
  command: mongodump --username {{ mongo_database_username }} --password {{ mongo_database_passwd }} --collection {{ mongo_collection_name }} --db {{ mongo_database_name }} --out {{ mongo_backup_dir }}
  when: backup_for_spaecfice_collection

- name: mongo backup.zip
  command: tar -cvf {{ mongo_backup_dir }}/{{ ansible_hostname }}-{{ ansible_date_time.date }}:{{ ansible_date_time.time }}-backup.tar.gz {{ mongo_backup_dir }}
  
- name: upload in s3 bucket ...C
  command: aws s3 cp {{ mongo_backup_dir }}/{{ ansible_hostname }}-{{ ansible_date_time.date }}:{{ ansible_date_time.time }}-backup.tar.gz s3://{{ s3_buket_name }}

