---
# tasks file for opstree.mongo

- name: Creates backup directory ...
  file: path={{ backup_dir }} state=directory

- name: mongo backup ...
  command: mongodump --out {{ backup_dir }}
  when: password_less_login

- name: mongo backup ...
  command: mongodump --username {{ userName }} --password {{ passWd }} --out {{ backup_dir }}
  when: password_login

- name: mongo backup.zip
  command: tar -cvf {{ backup_dir }}/backup.tar.gz {{ backup_dir }}
  
- name: upload in s3 bucket ...
  command: aws s3 cp {{ backup_dir }}/backup.tar.gz s3://{{ buket_name }}/{{ aws_dir_name }}.tar.gz

